name: deploy-web
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev
      - run: go build -o web/maze.wasm cmd/app/main.go
        env:
          GOOS: js
          GOARCH: wasm
      - run: cp $(go env GOROOT)/misc/wasm/wasm_exec.js web
      - run: go test -v ./...
        env:
          DISPLAY: ':99.0'

      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v2
        with:
          path: web
      - id: deployment
        uses: actions/deploy-pages@v3